# =========================
# Kitty - Lain Pink Theme
# =========================

# Font
font_family JetBrains Mono NL
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12.0

# Window
background #000000
foreground #f8f8f2
background_opacity 0.65
dynamic_background_opacity yes
window_padding_width 10
confirm_os_window_close 0
enable_audio_bell no

# Cursor
cursor #ff5774
cursor_text_color #000000
cursor_shape beam
cursor_blink_interval 0.5

# Selection
selection_foreground #000000
selection_background #ff7a99

# URL
url_color #ff8ba6
url_style curly

# Tabs
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_edge bottom

active_tab_foreground #000000
active_tab_background #ff7a99
inactive_tab_foreground #f8f8f2
inactive_tab_background #282a36

# =========================
# Colors
# =========================

# black
color0  #000000
color8  #4d4d4d

# red
color1  #ff5774
color9  #ff6580

# green
color2  #6ae98a
color10 #70f893

# yellow
color3  #ffe099
color11 #ffe6ad

# blue / pink-blue
color4  #ff7a99
color12 #ff8ba6

# magenta
color5  #e0b2a5
color13 #e8c4bb

# cyan / cream
color6  #efdaa1
color14 #ffe8ac

# white
color7  #bfbfbf
color15 #e6e6e6

# Shortcuts
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+f5 load_config_file
